//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace barCodeEntity
{
    using System;
    

    
    public sealed class barCodeReportEntity
    {
        public barCodeReportEntity ( )
        {
        }
        
        private int _idx;
        
        private string _bar001;
        
        private string _bar002;
        
        private string _bar003;
        
        private string _bar004;
        
        private string _bar005;
        
        private string _bar006;
        
        private string _bar007;
        
        private string _bar008;
        
        private string _bar009;
        
        private string _bar010;
        
        private string _bar011;
        
        private string _bar012;
        
        private string _bar013;
        
        private DateTime _bar014;
        
        private DateTime _bar015;
        
        private string _bar016;
        
        private string _bar017;
        
        private string _bar018;
        
        private int _bar019;
        
        private int _bar020;
        
        private decimal _bar021;
        
        private DateTime _bar022;
        
        private int _bar023;
        
        private DateTime? _bar024;
        
        private string _bar025;
        
        private string _bar026;
        
        private string _bar027;
        
        private string _bar028;
        
        private string _bar029;
        
        private string _bar030;

        private bool _check;
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        public bool Check
        {
            get
            {
                return _check;
            }
            set
            {
                this . _check = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string BAR001
        {
            get
            {
                return this._bar001;
            }
            set
            {
                this._bar001 = value;
            }
        }

        /// <summary>
        /// Product
        /// </summary>

        public string BAR002
        {
            get
            {
                return this._bar002;
            }
            set
            {
                this._bar002 = value;
            }
        }

        /// <summary>
        /// Type
        /// </summary>

        public string BAR003
        {
            get
            {
                return this._bar003;
            }
            set
            {
                this._bar003 = value;
            }
        }

        /// <summary>
        /// Spec.
        /// </summary>

        public string BAR004
        {
            get
            {
                return this._bar004;
            }
            set
            {
                this._bar004 = value;
            }
        }

        /// <summary>
        /// Packing
        /// </summary>

        public string BAR005
        {
            get
            {
                return this._bar005;
            }
            set
            {
                this._bar005 = value;
            }
        }

        /// <summary>
        /// 型号
        /// </summary>

        public string BAR006
        {
            get
            {
                return this._bar006;
            }
            set
            {
                this._bar006 = value;
            }
        }

        /// <summary>
        /// 轴号
        /// </summary>

        public string BAR007
        {
            get
            {
                return this._bar007;
            }
            set
            {
                this._bar007 = value;
            }
        }

        /// <summary>
        /// Lot ID
        /// </summary>

        public string BAR008
        {
            get
            {
                return this._bar008;
            }
            set
            {
                this._bar008 = value;
            }
        }

        /// <summary>
        /// 订单单号
        /// </summary>

        public string BAR009
        {
            get
            {
                return this._bar009;
            }
            set
            {
                this._bar009 = value;
            }
        }

        /// <summary>
        /// 出库单号
        /// </summary>

        public string BAR010
        {
            get
            {
                return this._bar010;
            }
            set
            {
                this._bar010 = value;
            }
        }

        /// <summary>
        /// 入库单号
        /// </summary>

        public string BAR011
        {
            get
            {
                return this._bar011;
            }
            set
            {
                this._bar011 = value;
            }
        }

        /// <summary>
        /// 入库标记
        /// </summary>

        public string BAR012
        {
            get
            {
                return this._bar012;
            }
            set
            {
                this._bar012 = value;
            }
        }

        /// <summary>
        /// 出库标记
        /// </summary>

        public string BAR013
        {
            get
            {
                return this._bar013;
            }
            set
            {
                this._bar013 = value;
            }
        }

        /// <summary>
        /// 入库时间
        /// </summary>

        public DateTime BAR014
        {
            get
            {
                return this._bar014;
            }
            set
            {
                this._bar014 = value;
            }
        }

        /// <summary>
        /// 出库时间
        /// </summary>

        public DateTime BAR015
        {
            get
            {
                return this._bar015;
            }
            set
            {
                this._bar015 = value;
            }
        }

        /// <summary>
        /// 扫描状态
        /// </summary>

        public string BAR016
        {
            get
            {
                return this._bar016;
            }
            set
            {
                this._bar016 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string BAR017
        {
            get
            {
                return this._bar017;
            }
            set
            {
                this._bar017 = value;
            }
        }
        
        /// <summary>
        /// 流水号
        /// </summary>
                 
        public string BAR018
        {
            get
            {
                return this._bar018;
            }
            set
            {
                this._bar018 = value;
            }
        }

        /// <summary>
        /// 入库数量
        /// </summary>

        public int BAR019
        {
            get
            {
                return this._bar019;
            }
            set
            {
                this._bar019 = value;
            }
        }

        /// <summary>
        /// 出库数量
        /// </summary>

        public int BAR020
        {
            get
            {
                return this._bar020;
            }
            set
            {
                this._bar020 = value;
            }
        }

        /// <summary>
        /// 平均克重
        /// </summary>

        public decimal BAR021
        {
            get
            {
                return this._bar021;
            }
            set
            {
                this._bar021 = value;
            }
        }
        
        /// <summary>
        /// 打印时间
        /// </summary>
                 
        public DateTime BAR022
        {
            get
            {
                return this._bar022;
            }
            set
            {
                this._bar022 = value;
            }
        }
        
        /// <summary>
        /// 本次入库数量
        /// </summary>
                 
        public int BAR023
        {
            get
            {
                return this._bar023;
            }
            set
            {
                this._bar023 = value;
            }
        }
        
        /// <summary>
        /// 生产日期
        /// </summary>
                 
        public DateTime? BAR024
        {
            get
            {
                return this._bar024;
            }
            set
            {
                this._bar024 = value;
            }
        }

        /// <summary>
        /// 批号说明
        /// </summary>

        public string BAR025
        {
            get
            {
                return this._bar025;
            }
            set
            {
                this._bar025 = value;
            }
        }
        
        // 
        public string BAR026
        {
            get
            {
                return this._bar026;
            }
            set
            {
                this._bar026 = value;
            }
        }
        
        // 
        public string BAR027
        {
            get
            {
                return this._bar027;
            }
            set
            {
                this._bar027 = value;
            }
        }
        
        // 
        public string BAR028
        {
            get
            {
                return this._bar028;
            }
            set
            {
                this._bar028 = value;
            }
        }
        
        // 
        public string BAR029
        {
            get
            {
                return this._bar029;
            }
            set
            {
                this._bar029 = value;
            }
        }
        
        // 
        public string BAR030
        {
            get
            {
                return this._bar030;
            }
            set
            {
                this._bar030 = value;
            }
        }
    }
}
